substitutions:
  _REGION: us-central1
  _REPO: online-boutique

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    id: Build-Frontend
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/frontend:latest
      - src/frontend

  # repeat for other services...

  - name: gcr.io/cloud-builders/kubectl
    id: Deploy-To-GKE
    args: ["apply", "-f", "release/kubernetes-manifests.yaml"]
    env:
      - CLOUDSDK_COMPUTE_REGION=${_REGION}
      - CLOUDSDK_CONTAINER_CLUSTER=online-boutique

images:
